/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp7;

import java.util.HashSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class FormularioInscripcion extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form FormularioInscripcion
     */
    public FormularioInscripcion() {
        initComponents();
        llenarCombo1();
        llenarCombo2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlElijaMat = new javax.swing.JLabel();
        jbSalir = new javax.swing.JButton();
        jlElijaAl = new javax.swing.JLabel();
        jbInscribir = new javax.swing.JButton();
        jcbElijaMat = new javax.swing.JComboBox<>();
        jcbElijaAl = new javax.swing.JComboBox<>();

        setClosable(true);

        jlTitulo.setFont(new java.awt.Font("Modern No. 20", 1, 14)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(102, 0, 102));
        jlTitulo.setText("FORMULARIO DE INSCRIPCIÓN");

        jlElijaMat.setFont(new java.awt.Font("Modern No. 20", 1, 11)); // NOI18N
        jlElijaMat.setForeground(new java.awt.Color(51, 0, 51));
        jlElijaMat.setText("Elija una materia");

        jbSalir.setForeground(new java.awt.Color(51, 0, 51));
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jlElijaAl.setFont(new java.awt.Font("Modern No. 20", 1, 11)); // NOI18N
        jlElijaAl.setForeground(new java.awt.Color(51, 0, 51));
        jlElijaAl.setText("Elija un Alumno");

        jbInscribir.setForeground(new java.awt.Color(51, 0, 51));
        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jcbElijaMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbElijaMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jlTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlElijaAl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcbElijaAl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlElijaMat, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jcbElijaMat, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbInscribir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalir)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlElijaMat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbElijaMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlElijaAl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbElijaAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir)
                    .addComponent(jbInscribir))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jcbElijaMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbElijaMatActionPerformed
        
    }//GEN-LAST:event_jcbElijaMatActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        // TODO add your handling code here:
        //Alumno al = MenuPrincipal.getAlumnos().agregarMaterias();
        Materia mat = (Materia)jcbElijaMat.getSelectedItem();
        Alumno a1umno = (Alumno) jcbElijaAl.getSelectedItem();
        if(mat==null||a1umno==null){
            JOptionPane.showMessageDialog(this,"Falta un campo");
        }
        else {
        if(a1umno.agregarMateria(mat)==1){
            JOptionPane.showMessageDialog(this,"Inscripción realizada");}
        else {
            JOptionPane.showMessageDialog(this,"Materia ya inscripta");}
        }
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void llenarCombo1() {
        HashSet<Materia> mat = MenuPrincipal.getMaterias();
        for (Materia m : mat) {
            jcbElijaMat.addItem(m);
        }
        jcbElijaMat.setSelectedIndex(-1);
    }
    private void llenarCombo2() {
        HashSet<Alumno> al = MenuPrincipal.getAlumnos();
        for (Alumno a : al) {
            jcbElijaAl.addItem(a);
        }
        jcbElijaAl.setSelectedIndex(-1);
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Alumno> jcbElijaAl;
    private javax.swing.JComboBox<Materia> jcbElijaMat;
    private javax.swing.JLabel jlElijaAl;
    private javax.swing.JLabel jlElijaMat;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
