/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp7;

import java.util.HashSet;

/**
 *
 * @author Administrador
 */
public class MenuPrincipal extends javax.swing.JFrame {
  
    private static HashSet<Materia>materias = new HashSet<>();
     static HashSet<Alumno>alumnos = new HashSet<>();
    /**
     * Creates new form MenuPrincipañ
     */
    public MenuPrincipal() {
        initComponents();
    }

    public static HashSet<Materia> getMaterias() {
        return materias;
    }

    public static HashSet<Alumno> getAlumnos() {
        return alumnos;
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdEsc = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jmiAltaMaterias = new javax.swing.JMenuItem();
        jmiAltaAlumnos = new javax.swing.JMenuItem();
        jmiFormularioInscripcion = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdEsc.setBackground(new java.awt.Color(204, 102, 255));

        javax.swing.GroupLayout jdEscLayout = new javax.swing.GroupLayout(jdEsc);
        jdEsc.setLayout(jdEscLayout);
        jdEscLayout.setHorizontalGroup(
            jdEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdEscLayout.setVerticalGroup(
            jdEscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu.setForeground(new java.awt.Color(51, 0, 51));
        jMenu.setText("Menú");

        jmiAltaMaterias.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jmiAltaMaterias.setForeground(new java.awt.Color(51, 0, 51));
        jmiAltaMaterias.setText("Alta de Materias");
        jmiAltaMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAltaMateriasActionPerformed(evt);
            }
        });
        jMenu.add(jmiAltaMaterias);

        jmiAltaAlumnos.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jmiAltaAlumnos.setForeground(new java.awt.Color(51, 0, 51));
        jmiAltaAlumnos.setText("Alta de Alumnos");
        jmiAltaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAltaAlumnosActionPerformed(evt);
            }
        });
        jMenu.add(jmiAltaAlumnos);

        jmiFormularioInscripcion.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jmiFormularioInscripcion.setForeground(new java.awt.Color(51, 0, 51));
        jmiFormularioInscripcion.setText("Formulario de Inscripción");
        jmiFormularioInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioInscripcionActionPerformed(evt);
            }
        });
        jMenu.add(jmiFormularioInscripcion);

        jMenuBar1.add(jMenu);

        jmSalir.setText("Salir");
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEsc)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdEsc)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAltaMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaMateriasActionPerformed
        // TODO add your handling code here:
        jdEsc.removeAll();
        jdEsc.repaint();
        FormularioMaterias var = new FormularioMaterias();
        var.setVisible(true);
        jdEsc.add(var);
    }//GEN-LAST:event_jmiAltaMateriasActionPerformed

    private void jmiAltaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaAlumnosActionPerformed
        // TODO add your handling code here:
        jdEsc.removeAll();
        jdEsc.repaint();
        FormularioAlumnos var = new FormularioAlumnos();
        var.setVisible(true);
        jdEsc.add(var);
    }//GEN-LAST:event_jmiAltaAlumnosActionPerformed

    private void jmiFormularioInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioInscripcionActionPerformed
        // TODO add your handling code here:
        jdEsc.removeAll();
        jdEsc.repaint();
        FormularioInscripcion var = new FormularioInscripcion();
        var.setVisible(true);
        jdEsc.add(var);
    }//GEN-LAST:event_jmiFormularioInscripcionActionPerformed

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jmSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdEsc;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAltaAlumnos;
    private javax.swing.JMenuItem jmiAltaMaterias;
    private javax.swing.JMenuItem jmiFormularioInscripcion;
    // End of variables declaration//GEN-END:variables
}
